# sonar-project.properties
sonar.projectKey=mi-repo-pico-placa
sonar.projectName=PicoPlacaApp
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
# sonar.host.url and sonar.login will be proporcionados por Jenkins environment
