apiVersion: apps/v1
kind: Deployment
metadata:
  name: pico-placa-app
  labels:
    app: pico-placa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pico-placa
  template:
    metadata:
      labels:
        app: pico-placa
    spec:
      containers:
        - name: pico-placa
          image: ricardovaca109/pico-placa:latest
          ports:
            - containerPort: 5000
          env:
            - name: LAUNCHDARKLY_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-secret
                  key: sdk-key
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
